Repository stack-of-tasks/pinocchio, pull requests merged in 2024-12, with the labels that each got.

#2503 Fix meshcat examples
  CHANGELOG.md
  examples/append-urdf-model-with-another-model.py
  examples/collision-with-point-clouds.py
  examples/meshcat-viewer-octree.py
  examples/meshcat-viewer-solo.py
Labels: build_collision

#2502 Fix coal integration
  .github/workflows/update_pixi_lockfile.yml
  CHANGELOG.md
  examples/casadi/quadrotor-ocp.py
  unittest/parallel-geometry.cpp
Labels: build_all

#2511 Fix scaling support for meshcat
  CHANGELOG.md
  bindings/python/pinocchio/visualize/meshcat_visualizer.py
Labels: build_collision

#2514 fix: fix typo
  doc/d-practical-exercises/1-directgeom.md
  doc/d-practical-exercises/2-invgeom.md
  include/pinocchio/algorithm/geometry.hpp
Labels: no changelog

#2517 Activate collision specific features in pinocchio_default
  .github/workflows/linux.yml
  CHANGELOG.md
  CMakeLists.txt
  src/CMakeLists.txt
Labels: build_collision
