Repository stack-of-tasks/pinocchio, pull requests merged in 2024-09, with the labels that each got.

#2405 Pre commit fix
  .git-blame-ignore-revs
  README.md
Labels: no changelog

#2404 Nix
  .github/workflows/nix.yml
  flake.lock
  flake.nix
Labels: no changelog

#2409 doc: Document the JointModelFreeFlyerTpl structure
  include/pinocchio/multibody/joint/joint-free-flyer.hpp
Labels: no changelog

#2407 doc: Fix orphaned documentation pages for Features
  doc/a-features/a-spatial.md
  doc/a-features/b-model-data.md
  doc/a-features/c-joints.md
  doc/a-features/d-model.md
  doc/a-features/e-lie.md
  doc/a-features/f-kinematic.md
  doc/a-features/g-dynamic.md
  doc/a-features/h-frames.md
  doc/a-features/i-geometric-models.md
  doc/a-features/intro.md
  doc/a-features/j-analytical-derivatives.md
  doc/a-features/k-automatic-differentiation.md
  doc/a-features/l-python.md
  doc/a-features/m-tests.md
  doc/c-maths/a-rigid-bodies.md
  doc/treeview.dox
Labels: no changelog

#2416 contact-info: cache nv, fix #2304
  CHANGELOG.md
  include/pinocchio/algorithm/contact-info.hpp
Labels: build_all

#2419 configurable default visualizer
  CHANGELOG.md
  bindings/python/CMakeLists.txt
  bindings/python/pinocchio/robot_wrapper.py
  bindings/python/pinocchio/visualize/__init__.py
  bindings/python/pinocchio/visualize/visualizers.py
Labels: build_collision

#2415 doc - Add explanations for null space projection.
  doc/d-practical-exercises/3-invkine.md
Labels: no changelog

#2430 Fix ruff warnings
  bindings/python/pinocchio/visualize/rviz_visualizer.py
  examples/inverse-kinematics-3d.py
Labels: no changelog

#2402 Update Model parsing
  CHANGELOG.md
  bindings/python/parsers/mjcf/model.cpp
  bindings/python/parsers/sdf/model.cpp
  bindings/python/parsers/urdf/model.cpp
  bindings/python/pinocchio/robot_wrapper.py
  bindings/python/pinocchio/shortcuts.py
  bindings/python/utils/dependencies.cpp
  include/pinocchio/parsers/mjcf.hpp
  include/pinocchio/parsers/mjcf/model.hxx
  include/pinocchio/parsers/sdf.hpp
  include/pinocchio/parsers/sdf/model.hxx
  include/pinocchio/parsers/urdf.hpp
  include/pinocchio/parsers/urdf/model.hxx
  src/parsers/sdf/geometry.cpp
  unittest/contact-dynamics-derivatives.cpp
  unittest/mjcf.cpp
  unittest/python/robot_wrapper.py
  unittest/sdf.cpp
  unittest/urdf.cpp
Labels: build_sdf
