Repository stack-of-tasks/pinocchio, pull requests merged in 2024-08, with the labels that each got.

#2363 Add BuildFromMJCF function to RobotWrapper
  CHANGELOG.md
  bindings/python/pinocchio/robot_wrapper.py
  unittest/python/CMakeLists.txt
  unittest/python/robot_wrapper.py
Labels: build_collision, build_all

#2366 doc - Correct null space projection formula.
  doc/d-practical-exercises/3-invkine.md
Labels: no changelog, build_accelerate

#2369 Fix message and build_all label
  .github/workflows/check_label.yml
  .github/workflows/scripts/check_label.js
  .github/workflows/scripts/get_label.js
Labels: no changelog

#2370 Fix compatibility with NumPy 2.x
  include/pinocchio/bindings/python/context/casadi.hpp
Labels: no changelog

#2371 Fix printing of the options
  .github/workflows/scripts/check_label.js
Labels: no changelog

#2388 Restructure CppAD and CasADi examples
  CHANGELOG.md
  bindings/python/CMakeLists.txt
  examples/CMakeLists.txt
  examples/casadi/CMakeLists.txt
  examples/casadi/cartpole.py
  examples/casadi/casadi-aba.cpp
  examples/casadi/casadi-rnea.cpp
  examples/casadi/quadrotor-ocp.py
  examples/casadi/simulation-pendulum-variational.ipynb
  examples/cppad/CMakeLists.txt
  examples/cppad/autodiff-rnea.cpp
  examples/cppad/autodiff-rnea.py
  include/pinocchio/autodiff/casadi.hpp
Labels: build_casadi
