Repository stack-of-tasks/pinocchio, pull requests merged in 2025-06, with the labels that each got.

#2686 CMake: add COAL_DISABLE_HPP_FCL_WARNINGS
  .github/workflows/nix.yml
  CHANGELOG.md
  CMakeLists.txt
  benchmark/CMakeLists.txt
  bindings/python/CMakeLists.txt
  examples/CMakeLists.txt
  flake.nix
  src/CMakeLists.txt
  unittest/CMakeLists.txt
  unittest/python/CMakeLists.txt
Labels: build_all, pr status to review

#2707 Fix : make nvSubtree consistent with mimic joint in all configuration
  CHANGELOG.md
  include/pinocchio/algorithm/check-data.hxx
  include/pinocchio/multibody/data.hxx
  unittest/utils/model-generator.hpp
Labels: build_all

#2717 CMakeLists.txt: remove a duplicate option()
  CMakeLists.txt
Labels: no changelog

#2713 Add arm running in pixi workflow
  .github/workflows/macos-linux-windows-pixi.yml
  pixi.lock
  pixi.toml
  unittest/algorithm/utils/force.cpp
Labels: no changelog, pr status to review

#2715 Fix hasConfigurationLimit() for mimic joints to return empty vector
  CHANGELOG.md
  include/pinocchio/multibody/joint/joint-mimic.hpp
  unittest/model.cpp
Labels: pr status ready
