Repository stack-of-tasks/pinocchio, pull requests merged in 2025-04, with the labels that each got.

#2633 Update readme
  README.md
Labels: no changelog

#2637 Add CRBA CasADi example
  examples/casadi/CMakeLists.txt
  examples/casadi/casadi-crba.cpp
  include/pinocchio/spatial/inertia.hpp
  unittest/casadi/spatial.cpp
Labels: no changelog, build_casadi

#2644 [Model] Improve error message
  include/pinocchio/multibody/model.hxx
Labels: no changelog

#2648 unittest/python : add visualizer bindings visitor test, add CMake util to create C++ Python modules for tests
  include/pinocchio/bindings/python/visualizers/visualizer-visitor.hpp
  unittest/python/CMakeLists.txt
  unittest/python/bindings_visualizer.cpp
  unittest/python/bindings_visualizer.py
Labels: no changelog

#2668 Implement `captureImage` for Panda3D visualizer
  CHANGELOG.md
  bindings/python/pinocchio/visualize/panda3d_visualizer.py
  examples/panda3d-viewer-play.py
Labels: pr status to review
