Repository stack-of-tasks/pinocchio, pull requests merged in 2025-03, with the labels that each got.

#2591 CMake: fix for hpp-fcl/coal v3
  CMakeLists.txt
Labels: no changelog, build_collision

#2528 Add missing Python example for testing
  CHANGELOG.md
  examples/CMakeLists.txt
  examples/simulation-closed-kinematic-chains.py
  include/pinocchio/algorithm/jacobian.hxx
  include/pinocchio/multibody/data.hxx
  include/pinocchio/multibody/joint/joint-mimic.hpp
  unittest/python/CMakeLists.txt
Labels: build_collision, pr status to review

#2608 Enhacing casting support for multiple floating-point scalars and Casadi and CppAD types
  CHANGELOG.md
  include/pinocchio/autodiff/casadi/math/quaternion.hpp
  include/pinocchio/autodiff/cppad/math/quaternion.hpp
  include/pinocchio/bindings/python/spatial/explog.hpp
  include/pinocchio/codegen/cppadcg.hpp
  include/pinocchio/math/quaternion.hpp
  include/pinocchio/multibody/data.hxx
  include/pinocchio/multibody/joint/joint-basic-visitors.hxx
  include/pinocchio/multibody/joint/joint-mimic.hpp
  include/pinocchio/multibody/liegroup/special-euclidean.hpp
  include/pinocchio/multibody/liegroup/special-orthogonal.hpp
  src/parsers/mjcf/mjcf-graph-geom.cpp
  unittest/all-joints.cpp
  unittest/data.cpp
  unittest/utils/model-generator.hpp
Labels: need modifications, priority, build_casadi, build_autodiff, build_codegen, pr status to review

#2623 Update ROS CI
  .github/workflows/ros_ci.yml
Labels: no changelog

#2607 Use google benchmark instead of our legacy benchmark system
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  benchmark/CMakeLists.txt
  benchmark/README.md
  benchmark/model-fixture.hpp
  benchmark/plot.py
  benchmark/timings-cg.cpp
  benchmark/timings-cholesky.cpp
  benchmark/timings-constrained-dynamics-derivatives.cpp
  benchmark/timings-contact-dynamics.cpp
  benchmark/timings-cppad-jit.cpp
  benchmark/timings-delassus-operations.cpp
  benchmark/timings-derivatives.cpp
  benchmark/timings-eigen.cpp
  benchmark/timings-geometry.cpp
  benchmark/timings-impulse-dynamics-derivatives.cpp
  benchmark/timings-impulse-dynamics.cpp
  benchmark/timings-jacobian.cpp
  benchmark/timings-parallel.cpp
  benchmark/timings.cpp
  development/scripts/pixi/activation.bat
  development/scripts/pixi/activation.sh
  include/pinocchio/algorithm/contact-cholesky.hxx
  include/pinocchio/macros.hpp
  include/pinocchio/multibody/joint/joint-free-flyer.hpp
  include/pinocchio/multibody/joint/joint-helical.hpp
  include/pinocchio/multibody/joint/joint-mimic.hpp
  include/pinocchio/multibody/joint/joint-revolute.hpp
  include/pinocchio/multibody/joint/joint-spherical.hpp
  pixi.lock
  pixi.toml
Labels: pr status to review

#2626 Set back PINOCCHIO_DEFAULT_QUATERNION_NORM_TOLERANCE_VALUE definition
  include/pinocchio/math/quaternion.hpp
Labels: no changelog, pr status to review

#2624 Fix ModelTpl::check() link
  CHANGELOG.md
  include/pinocchio/algorithm/contact-cholesky.hxx
  include/pinocchio/algorithm/contact-jacobian.hxx
Labels: build_all, pr status to review

#2627 Fix PCH and ccache build
  .github/workflows/linux.yml
  .github/workflows/macos-linux-windows-pixi.yml
  .github/workflows/ros_ci.yml
  bindings/python/CMakeLists.txt
  development/scripts/pixi/activation.bat
  development/scripts/pixi/activation.sh
  development/scripts/pixi/activation_clang.sh
Labels: no changelog, pr status wip

#2630 Update README.md for new minimal C++ version
  README.md
Labels: documentation, no changelog
