Repository stack-of-tasks/pinocchio, pull requests merged in 2025-09, with the labels that each got.

#2714 CMake: add BUILD_STANDALONE_PYTHON_INTERFACE option
  .github/workflows/macos-linux-windows-pixi.yml
  .github/workflows/nix.yml
  CHANGELOG.md
  CMakeLists.txt
  bindings/python/CMakeLists.txt
  examples/CMakeLists.txt
  examples/casadi/CMakeLists.txt
  examples/codegen/CMakeLists.txt
  examples/cppad/CMakeLists.txt
  flake.lock
  flake.nix
  src/CMakeLists.txt
  unittest/CMakeLists.txt
  unittest/casadi/CMakeLists.txt
  unittest/cppad/CMakeLists.txt
  unittest/cppadcg/CMakeLists.txt
  unittest/python/CMakeLists.txt
Labels: build_all

#2743 Fix/cannot found casadi
  CHANGELOG.md
  CMakeLists.txt
  bindings/python/CMakeLists.txt
  src/CMakeLists.txt
  unittest/casadi/CMakeLists.txt
Labels: build_casadi

#2755 flake.lock: Update
  flake.lock
Labels: no changelog
